crm/urls.py
from django.conf.urls import url
from crm.views import consultant, teacher

urlpatterns = [
    url(r'^login/$', consultant.Login.as_view(), name='login'),
    url(r'^reg/$', consultant.reg, name='reg'),
    # 公户
    url(r'^customers/$', consultant.Customer.as_view(), name='customers'),
    # 私户
    url(r'^my_customers/$', consultant.Customer.as_view(), name='my_customers'),

    url(r'^add_customer/$', consultant.customer_change, name='add_customer'),
    url(r'^edit_customer/(\d+)/$', consultant.customer_change, name='edit_customer'),
    # 展示是某个销售的所有的跟进记录
    url(r'^consult_record/$', consultant.ConsultRecord.as_view(), name='consult_record'),

    # 展示是某个客户的所有的跟进记录
    url(r'^consult_record/(\d+)/$', consultant.ConsultRecord.as_view(), name='one_consult_record'),

    url(r'^add_consult_record/$', consultant.consult_record_change, name='add_consult_record'),
    url(r'^edit_consult_record/(\d+)/$', consultant.consult_record_change, name='edit_consult_record'),

    url(r'^enrollment_record/(?P<customer_id>\d+)/$', consultant.EnrollmentRecord.as_view(), name='enrollment_record'),
    url(r'^add_enrollment_record/(?P<customer_id>\d+)/$', consultant.enrollment_record_change,
        name='add_enrollment_record'),
    url(r'^edit_enrollment_record/(?P<pk>\d+)/$', consultant.enrollment_record_change, name='edit_enrollment_record'),

    url(r'^class_list/$', teacher.Classes.as_view(), name='class_list'),

    url(r'^add_class/$', teacher.class_change, name='add_class'),
    url(r'^edit_class/(\d+)/$', teacher.class_change, name='edit_class'),

    url(r'^course_record/(?P<class_id>\d+)/$', teacher.CourseRecordList.as_view(), name='course_record'),

    url(r'^add_course_record/(?P<class_id>\d+)/$', teacher.course_record_change, name='add_course_record'),
    url(r'^edit_course_record/(?P<pk>\d+)/$', teacher.course_record_change, name='edit_course_record'),

    url(r'^study_record/(?P<course_record_id>\d+)/$', teacher.study_record, name='study_record'),

]

old_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('crm.urls')),


]

crm/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (
    ('fulltime', '脱产班',),
    ('online', '网络班'),
    ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)

pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)

    def __str__(self):
        return "{} - {}".format(self.qq, self.name)

    def show_class(self):
        return ' , '.join([str(i) for i in self.class_list.all()])

    def show_status(self):
        """
        ('signed', "已报名"),
         ('unregistered', "未报名"),
         ('studying', '学习中'),
         ('paid_in_full', "学费已交齐")

        """
        color_dict = {
            'signed': 'green',
            'unregistered': 'red',
            'studying': 'yellow',
            'paid_in_full': 'pink',
        }

        return mark_safe(
            '<span style="color: white;background: {};padding: 3px">{}</span>'.format(color_dict[self.status],
                                                                                      self.get_status_display()))


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{} {}期 ({})".format(self.get_course_display(), self.semester, self.campuses)

    def show_teachers(self):
        return ' , '.join([str(i) for i in self.teachers.all()])


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses', verbose_name='校区')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', related_name='course_records', verbose_name="讲师")
    recorder = models.ForeignKey('UserProfile', verbose_name="记录者")

    class Meta:
        unique_together = ('re_class', 'day_num')

    def __str__(self):

crm/views/base.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.views import View
from django.db.models import Q


class ShowList(View):
    def post(self, request, *args, **kwargs):
        action = request.POST.get('action')

        func = getattr(self, action, None)
        if not func:
            # 方法未定义
            return HttpResponse('非法操作')
        # 执行相应的方法
        ret = func()
        if ret:
            return ret

        return self.get(request, *args, **kwargs)

    def search(self, filed_name):
        query = self.request.GET.get('query', '')

        q = Q()
        q.connector = 'OR'
        for field in filed_name:
            q.children.append(Q(('{}__contains'.format(field), query)))

        return q

crm/views/teacher.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.views import View
from crm import models
from utils.pagination import Pagination
import hashlib
from crm.forms import ClassListForm, CourseRecordForm, StudyRecordForm
from django.db.models import Q
from .base import ShowList


class Classes(ShowList):

    def get(self, request, *args, **kwargs):
        q = self.search([])

        all_class_list = models.ClassList.objects.filter(q)

        return render(request, 'teacher/class.html', {'all_class_list': all_class_list})


def class_change(request, pk=None):
    obj = models.ClassList.objects.filter(pk=pk).first()
    form_obj = ClassListForm(instance=obj)
    if request.method == 'POST':
        form_obj = ClassListForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect('class_list')
    title = '编辑班级' if pk else '新增班级'
    return render(request, 'form.html', {'form_obj': form_obj, 'title': title})


class CourseRecordList(ShowList):

    def get(self, request, class_id, *args, **kwargs):
        q = self.search([])

        all_course_records = models.CourseRecord.objects.filter(q, re_class_id=class_id)

        return render(request, 'teacher/course_record.html',
                      {'all_course_records': all_course_records, 'class_id': class_id})

    def multi_init(self):
        # 批量初始化学习记录

        pks = self.request.POST.get('pk')

        for pk in pks:
            # 一个课程记录
            course_record_obj = models.CourseRecord.objects.get(pk=pk)
            students = course_record_obj.re_class.customer_set.filter(status='studying')

            study_record_obj_list = []

            for student in students:

                if not models.StudyRecord.objects.filter(course_record=course_record_obj, student=student).exists():
                    study_record_obj_list.append(models.StudyRecord(course_record=course_record_obj, student=student))

            if study_record_obj_list:
                models.StudyRecord.objects.bulk_create(study_record_obj_list)


def course_record_change(request, class_id=None, pk=None):
    obj = models.CourseRecord(re_class_id=class_id,
                              recorder=request.user_obj) if class_id else models.CourseRecord.objects.filter(
        pk=pk).first()

    form_obj = CourseRecordForm(instance=obj)

    if request.method == 'POST':
        form_obj = CourseRecordForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            print(request.GET)
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect(reverse('course_record', args=(class_id,)))

    title = '新增课程记录'
    return render(request, 'form.html', {'form_obj': form_obj, 'title': title})


from django.forms import modelformset_factory


def study_record(request, course_record_id):
    ModelFormSet = modelformset_factory(models.StudyRecord, StudyRecordForm, extra=0)
    study_records = models.StudyRecord.objects.filter(course_record_id=course_record_id)
    formset = ModelFormSet(queryset=study_records)

    if request.method == 'POST':
        formset = ModelFormSet(request.POST)
        if formset.is_valid():
            formset.save()
        print(formset.errors)
    return render(request, 'teacher/study_record.html', {'formset': formset})

crm/templates/consultant/add_customer.html
{% extends 'layout.html' %}


{% block content %}


    <div class="panel panel-primary">
        <div class="panel-heading">新增客户</div>
        <div class="panel-body">

            <form class="form-horizontal" method="post" action="" novalidate>
                {% csrf_token %}

                {% for field in form_obj %}


                    <div class="form-group {% if field.errors %}has-error{% endif %} ">

                        <label {% if not field.field.required %}style="color: #666" {% endif %}
                               for="{{ field.id_for_label }}"
                               class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-7">
                            {{ field }}

                            <span class="help-block"> {{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>

            {#            <form action="" method="post" novalidate>#}
            {##}
            {#                {% csrf_token %}#}
            {##}
            {#                {{ form_obj.as_p }}#}
            {#                <button>提交</button>#}
            {#            </form>#}
        </div>
    </div>



{% endblock %}

crm/templates/consultant/consult_record.html
{% extends 'layout.html' %}


{% block content %}
    <div>
    <a class="btn btn-sm btn-primary" href="{% url 'add_consult_record' %}">新增</a>
    </div>

    <form action="" class="form-inline pull-right">

        <input type="text" name="query" class="form-control">
        <button class="btn btn-sm btn-success">搜索</button>

    </form>

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        <select name="action" class="form-control">
            <option value="multi_del">批量删除</option>

        </select>

        <button class="btn btn-sm btn-primary">提交</button>


        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>ID</th>
                <th>客户</th>
                <th>跟进内容</th>
                <th>跟进状态</th>
                <th>跟进日期</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for consult_record in all_consult_records %}
                <tr>
                    <td><input type="checkbox" name="pk" value="{{ consult_record.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ consult_record.pk }}</td>
                    <td>{{ consult_record.customer }}</td>
                    <td>{{ consult_record.note|truncatechars:100 }}</td>
                    <td>{{ consult_record.get_status_display }}</td>
                    <td>{{ consult_record.date}}</td>
                    <td>
                        {% load my_tags %}
                        <a class="btn btn-sm btn-success" href="{% reverse_url  request 'edit_consult_record' consult_record.pk %}">编辑</a>
                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </form>


    {{ page_html }}
{% endblock %}

crm/templates/consultant/customers.html
{% extends 'layout.html' %}


{% block content %}


    <form action="" class="form-inline pull-right">

        {#        <select name="field" class="form-control">#}
        {#            <option value="name">姓名</option>#}
        {#            <option value="qq">qq</option>#}
        {##}
        {#        </select>#}

        <input type="text" name="query" class="form-control">
        <button class="btn btn-sm btn-success">搜索</button>

    </form>

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        <select name="action" class="form-control">
            {% if request.path_info == url %}
                <option value="multi_apply">公户转私户</option>
            {% else %}
                <option value="multi_pub">私户转公户</option>

            {% endif %}

            <option value="multi_del">批量删除</option>

        </select>

        <button class="btn btn-sm btn-primary">提交</button>


        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>id</th>
                <th>QQ</th>
                <th>姓名</th>
{#                <th>性别</th>#}
                <th>手机号</th>
                <th>客户来源</th>
                <th>咨询课程</th>
                <th>班级类型</th>
                <th>状态</th>
                <th>最后跟进日期</th>
                <th>销售</th>
                <th>已报班级</th>
                <th>跟进记录</th>
                <th>报名记录</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for customer in all_customers %}
                <tr>
                    <td><input type="checkbox" name="pk" value="{{ customer.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ customer.pk }}</td>
                    <td>{{ customer.qq }}</td>
                    <td>{{ customer.name|default:'-' }}</td>
{#                    <td>{{ customer.get_sex_display }}</td>#}
                    <td>{{ customer.phone }}</td>
                    <td>{{ customer.get_source_display }}</td>
                    <td>{{ customer.course }}</td>
                    <td>{{ customer.get_class_type_display }}</td>
                    <td>{{ customer.show_status }}</td>
                    <td>{{ customer.last_consult_date }}</td>
                    <td>{{ customer.consultant }}</td>
                    <td>{{ customer.show_class }}</td>
                    <td><a href="{% url 'one_consult_record' customer.pk %}"> 查看</a></td>
                    <td>
                        <a href="{% url 'enrollment_record' customer.pk %}"> 查看</a>
                        <a href="{% url 'add_enrollment_record' customer.pk %}"> 新增</a>
                    </td>

                    <td>
                        {% load my_tags %}
                        <a href="{% reverse_url request 'edit_customer' customer.pk %}"><i class="fa fa-edit"> </i>
                        </a>



                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </form>


    {{ page_html }}
{% endblock %}

crm/templates/consultant/edit_customer.html
{% extends 'layout.html' %}


{% block content %}


    <div class="panel panel-primary">
        <div class="panel-heading">编辑客户</div>
        <div class="panel-body">

            <form class="form-horizontal" method="post" action="" novalidate>
                {% csrf_token %}

                {% for field in form_obj %}


                    <div class="form-group {% if field.errors %}has-error{% endif %} ">

                        <label {% if not field.field.required %}style="color: #666" {% endif %}
                               for="{{ field.id_for_label }}"
                               class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-7">
                            {{ field }}

                            <span class="help-block"> {{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>

            {#            <form action="" method="post" novalidate>#}
            {##}
            {#                {% csrf_token %}#}
            {##}
            {#                {{ form_obj.as_p }}#}
            {#                <button>提交</button>#}
            {#            </form>#}
        </div>
    </div>



{% endblock %}

crm/templates/consultant/enrollment_record.html
{% extends 'layout.html' %}


{% block content %}


    <table class="table table-bordered">
        <thead>
        <tr>
            <th>序号</th>
            <th>客户</th>
            <th>报名日期</th>
            <th>报名班级</th>
            <th>校区</th>
            <th>审批状态</th>
            <th>备注</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>

        {% for enrollment_record in all_enrollment_records %}
            <tr>

                <td>{{ forloop.counter }}</td>
                <td>{{ enrollment_record.customer }}</td>
                <td>{{ enrollment_record.enrolled_date }}</td>
                <td>{{ enrollment_record.enrolment_class }}</td>
                <td>{{ enrollment_record.school }}</td>
                <td>
                    {% if enrollment_record.contract_approved %}
                        通过
                    {% else %}
                        否
                    {% endif %}
                </td>
                <td>{{ enrollment_record.memo }}</td>
                <td>
                    {% load my_tags %}
                    <a href="{% reverse_url request 'edit_enrollment_record'  enrollment_record.pk %}">编辑</a>
                </td>
            </tr>

        {% endfor %}


        </tbody>

    </table>

{% endblock %}